name: Java CI with Gradle, PMD, and Checkstyle

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up JDK 21 with JavaFX
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: gradle

      - name: Install JavaFX SDK
        run: |
          mkdir -p ~/.javafx
          wget -O ~/.javafx/javafx-sdk.zip https://download2.gluonhq.com/openjfx/21/openjfx-21_linux-x64_bin-sdk.zip
          unzip ~/.javafx/javafx-sdk.zip -d ~/.javafx/
          mv ~/.javafx/javafx-sdk-21/* ~/.javafx/
          echo "JAVAFX_HOME=$HOME/.javafx" >> $GITHUB_ENV

      - name: Grant execute permission for Gradle wrapper
        run: chmod +x gradlew

      - name: Build (skip PMD/Checkstyle failures)
        run: ./gradlew build -x pmdMain -x pmdTest -x checkstyleMain -x checkstyleTest

      - name: Run Checkstyle (report only, don’t fail build)
        run: ./gradlew checkstyleMain checkstyleTest || true

      - name: Run PMD (report only, don’t fail build)
        run: ./gradlew pmdMain pmdTest || true

      - name: Install Python (for PMD report script)
        run: sudo apt-get update && sudo apt-get install -y python3 python3-pip

      - name: Run PMD Report Generator
        run: python3 scripts/generate_pmd_report.py

      - name: Upload PMD Report Artifact
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pmd-custom-report
          path: reports/

      - name: Upload Checkstyle Reports
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: checkstyle-reports
          path: build/reports/checkstyle/

      - name: Run Unit Tests (headless + tag filtering)
        run: ./gradlew test
